version: '2'

services:
  web:
    image: brunoluiz/pru-menus
    env_file: .env.development
    build:
      args:
        - NODE_ENV=development
      context: .
    volumes:
      - .:/opt/app
      - /opt/app/node_modules
    ports:
      - 8080:80
      - 9229:9229
    links:
      - mongodb:mongodb.host
    command: ../node_modules/.bin/nodemon -L ./app.js --inspect=0.0.0.0:9229

  mongodb:
    image: mongo:3.4
    # Port not exposed due to CircleCI
    # ports:
      # - '27017:27016'
